apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-demo
  name: react-service
  namespace: development
spec:
  type: NodePort
  selector:
    app: react-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080